### PR TITLE
teste 4

### PR DESCRIPTION
**Pull request by lmbleandro**

### CODE REVIEW

**Comment by lmbleandro** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_s3_bucket.b: Refreshing state... [id=lmb-my-tf-test-bucket]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_s3_bucket.b must be replaced
-/+ resource "aws_s3_bucket" "b" {
      + acceleration_status         = (known after apply)
      ~ arn                         = "arn:aws:s3:::lmb-my-tf-test-bucket" -> (known after apply)
      ~ bucket                      = "lmb-my-tf-test-bucket" -> "lmb1-my-tf-test-bucket" # forces replacement
      ~ bucket_domain_name          = "lmb-my-tf-test-bucket.s3.amazonaws.com" -> (known after apply)
      ~ bucket_regional_domain_name = "lmb-my-tf-test-bucket.s3.amazonaws.com" -> (known after apply)
      ~ hosted_zone_id              = "Z3AQBSTGFYJSTF" -> (known after apply)
      ~ id                          = "lmb-my-tf-test-bucket" -> (known after apply)
      ~ region                      = "us-east-1" -> (known after apply)
      ~ request_payer               = "BucketOwner" -> (known after apply)
        tags                        = {
            "Environment" = "Dev"
            "Name"        = "My bucket"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
        # (3 unchanged attributes hidden)

      ~ versioning {
          ~ enabled    = false -> (known after apply)
          ~ mfa_delete = false -> (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.cortex-intelligence.com/lock?id=lmbleandro%252Fatlantis-example%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lmbleandro** [comment]
atlantis apply

**Comment by lmbleandro** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by felipegfalcao — APPROVED** [review]

**Comment by lmbleandro** [comment]
terraform apply

**Comment by lmbleandro** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by lmbleandro** [comment]
atlantis apply

**Comment by lmbleandro** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_s3_bucket.b: Destroying... [id=lmb-my-tf-test-bucket]
aws_s3_bucket.b: Destruction complete after 0s
aws_s3_bucket.b: Creating...
aws_s3_bucket.b: Creation complete after 2s [id=lmb1-my-tf-test-bucket]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

```

**Comment by lmbleandro** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
